package aptech.dating.model;
// Generated Oct 30, 2023, 4:19:04 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Block generated by hbm2java
 */
@Entity
@Table(name = "block")
public class Block implements java.io.Serializable {

	private Integer id;
	private User userByBlockedId;
	private User userByUseId;

	public Block() {
	}

	public Block(User userByBlockedId, User userByUseId) {
		this.userByBlockedId = userByBlockedId;
		this.userByUseId = userByUseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	 @JsonIgnore @JoinColumn(name = "blocked_id", nullable = false)
	public User getUserByBlockedId() {
		return this.userByBlockedId;
	}

	public void setUserByBlockedId(User userByBlockedId) {
		this.userByBlockedId = userByBlockedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	 @JsonIgnore @JoinColumn(name = "user_id", nullable = false)
	public User getUserByUseId() {
		return this.userByUseId;
	}

	public void setUserByUseId(User userByUseId) {
		this.userByUseId = userByUseId;
	}

}
