package aptech.dating.model;
// Generated Oct 30, 2023, 4:19:04 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Exercise generated by hbm2java
 */
@Entity
@Table(name = "exercise")
public class Exercise implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<UserExercise> userExercises = new HashSet<UserExercise>(0);

	public Exercise() {
	}

	public Exercise(String name) {
		this.name = name;
	}

	public Exercise(String name, Set<UserExercise> userExercises) {
		this.name = name;
		this.userExercises = userExercises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercise")
	public Set<UserExercise> getUserExercises() {
		return this.userExercises;
	}

	public void setUserExercises(Set<UserExercise> userExercises) {
		this.userExercises = userExercises;
	}

}
