package aptech.dating.model;
// Generated Oct 30, 2023, 4:19:04 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Matching generated by hbm2java
 */
@Entity
@Table(name = "matching")
public class Matching implements java.io.Serializable {

	private Integer id;
	private User userBySecondUserId;
	private User userByFirstUserId;
	private int statusId;

	public Matching() {
	}

	public Matching(User userBySecondUserId, User userByFirstUserId, int statusId) {
		this.userBySecondUserId = userBySecondUserId;
		this.userByFirstUserId = userByFirstUserId;
		this.statusId = statusId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	 @JsonIgnore @JoinColumn(name = "second_user_id", nullable = false)
	public User getUserBySecondUserId() {
		return this.userBySecondUserId;
	}

	public void setUserBySecondUserId(User userBySecondUserId) {
		this.userBySecondUserId = userBySecondUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	 @JsonIgnore @JoinColumn(name = "first_user_id", nullable = false)
	public User getUserByFirstUserId() {
		return this.userByFirstUserId;
	}

	public void setUserByFirstUserId(User userByFirstUserId) {
		this.userByFirstUserId = userByFirstUserId;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

}
